// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG5OrsfGX1vlLCOmC0waU41XIni6fWSgQ',
    appId: '1:471317356342:web:8d36f052d53bdd21e6dd97',
    messagingSenderId: '471317356342',
    projectId: 'back-zaptalk',
    authDomain: 'back-zaptalk.firebaseapp.com',
    storageBucket: 'back-zaptalk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9oJOA03cBJxLOnwThF3K1sPD2isybj0',
    appId: '1:471317356342:android:c7e1a9be0dab2206e6dd97',
    messagingSenderId: '471317356342',
    projectId: 'back-zaptalk',
    storageBucket: 'back-zaptalk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAHV-p9xdyPHX6qgDrEqe91Mt47zfKJM',
    appId: '1:471317356342:ios:66ae718c1670ddbee6dd97',
    messagingSenderId: '471317356342',
    projectId: 'back-zaptalk',
    storageBucket: 'back-zaptalk.appspot.com',
    iosBundleId: 'com.example.zapTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdAHV-p9xdyPHX6qgDrEqe91Mt47zfKJM',
    appId: '1:471317356342:ios:66ae718c1670ddbee6dd97',
    messagingSenderId: '471317356342',
    projectId: 'back-zaptalk',
    storageBucket: 'back-zaptalk.appspot.com',
    iosBundleId: 'com.example.zapTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG5OrsfGX1vlLCOmC0waU41XIni6fWSgQ',
    appId: '1:471317356342:web:f2b11cbc4fffd100e6dd97',
    messagingSenderId: '471317356342',
    projectId: 'back-zaptalk',
    authDomain: 'back-zaptalk.firebaseapp.com',
    storageBucket: 'back-zaptalk.appspot.com',
  );
}
